<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>Warframe AIO Tool - Updater Beta</AssemblyName>
    <RootNamespace>GameLauncher</RootNamespace>
    <StartupObject>GameLauncher.BetaProgram</StartupObject>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <OutputPath>bin\BetaUpdater\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Product>Warframe AIO Tool — Updater Beta</Product>
    <Title>Warframe AIO Tool — Updater Beta</Title>
    <AssemblyTitle>Warframe AIO Tool — Updater Beta</AssemblyTitle>
    <Description>Warframe AIO Tool — Updater Beta Test Harness</Description>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Remove="System.Windows.Forms" />
    <Using Remove="System.Drawing" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\**\*.png" Exclude="Assets\OwHelper\**\*.*" />
    <Resource Include="Assets\**\*.wav" Exclude="Assets\OwHelper\**\*.*" />
    <EmbeddedResource Include="Musics\**\*.mp3" />
    <Content Include="Assets\OwHelper\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Update="Spoof resources\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
